# **Practice 04: Other Data Structures and Vectorization**

#### **Kelani Guyton**

---

**IMPORTANT**:
- Before starting the lab, save a copy to your google drive by navigating to `File > Save a copy in Drive` <br>

<br>


**Instructions**: Complete the lab below.

- <font color=red>Tasks</font> indicated in red must be completed to receive credit
- Include all code for your work
- Include markdown cells with written answers explaining your work when prompted
- **NOTE: Your completed lab must be submitted to Canvas as a .ipynb file by the end of the lab session**
---

<br>

####<font color=red>Organized</font>

**Answers should be organized in the following format for organization and readability**

<font color=red>Example task 1</font>

In [ ]:
# 1.

# This will be the code block to answer the first part of a task

1. This will be the text answer/explanation (if prompted) for the first task

<font color=red>Example task 2</font>

In [ ]:
# 2.

# This will be the code block to answer the second part of a task

2. This will be the text answer/explanation (if prompted) for the second task

<br>

Continue this format for the remaining subtasks

<br>

<br>

---

####<font color=red>Task 1</font> - Data frames - Initial Exploration

<font color=red>Task 1.1</font> Load the `mtcars` dataset by running `data(mtcars)`.

In [1]:
data(mtcars)

<br>

<font color=red>Task 1.2</font> View the first few lines of the `mtcars` data frame using the `head()` function.

In [2]:
head(mtcars)

                  mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

<br>

<font color=red>Task 1.3</font> Use the `str()` function to determine the number of rows and columns in the data frame.

In a text cell, write your answer in complete sentences.

In [3]:
str(mtcars)

'data.frame':	32 obs. of  11 variables:
 $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
 $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
 $ disp: num  160 160 108 258 360 ...
 $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
 $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
 $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
 $ qsec: num  16.5 17 18.6 19.4 17 ...
 $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
 $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
 $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
 $ carb: num  4 4 1 1 2 1 4 2 2 4 ...

There are 32 observations (rows) and 11 variables (columns) in the `mtcars` data fram. all variables are currently class `numerical`.

<br>

<font color=red>Task 1.4</font> Use the `names()` function to extract and view the variables in the `mtcars` data frame.

In [5]:
names(mtcars)

 [1] "mpg"  "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "gear"
[11] "carb"

<br>

<font color=red>Task 1.5</font> Use the `rownames()` function to extract and view the row names in the `mtcars` data frame. In a text cell, write your observations.

In [6]:
rownames(mtcars)

 [1] "Mazda RX4"           "Mazda RX4 Wag"       "Datsun 710"
 [4] "Hornet 4 Drive"      "Hornet Sportabout"   "Valiant"
 [7] "Duster 360"          "Merc 240D"           "Merc 230"
[10] "Merc 280"            "Merc 280C"           "Merc 450SE"
[13] "Merc 450SL"          "Merc 450SLC"         "Cadillac Fleetwood"
[16] "Lincoln Continental" "Chrysler Imperial"   "Fiat 128"
[19] "Honda Civic"         "Toyota Corolla"      "Toyota Corona"
[22] "Dodge Challenger"    "AMC Javelin"         "Camaro Z28"
[25] "Pontiac Firebird"    "Fiat X1-9"           "Porsche 914-2"
[28] "Lotus Europa"        "Ford Pantera L"      "Ferrari Dino"
[31] "Maserati Bora"       "Volvo 142E"

The row names are the make and model of the cars.

<br>

<font color=red>Task 1.6</font>

* Use the script `?mtcars` or search documentation online to determine the meaning of the variables.
* In a text cell, what is the definition of the variables `vs` and `am`?

In [7]:
?mtcars

The `vs` column is for engine shape. If the engine is V-shaped then the value is 0 and if the engine is S shapes then the value is 1. The `am` column stands for automatic (0) or manual (1) transmission.

<br>

<br>

<br>

---

####<font color=red>Task 2</font> - Cleaning Up Factors

From 1.6, it should be clear that the variables `vs` and `am` are categorical variables. Therefore, we should convert these into a `factor`.

<font color=red>Task 2.1</font> Convert the `vs` and `am` variables into a `factor` data structure using the `as.factor()` function and overwrite the variables in the `mtcars` data frame.

Use the `str()` function to verify these changes.

In [10]:
# convert `vs` and `am` to factor
mtcars$vs <- as.factor(mtcars$vs)
mtcars$am <- as.factor(mtcars$am)

# check class
str(mtcars)

'data.frame':	32 obs. of  11 variables:
 $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
 $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
 $ disp: num  160 160 108 258 360 ...
 $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
 $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
 $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
 $ qsec: num  16.5 17 18.6 19.4 17 ...
 $ vs  : Factor w/ 2 levels "0","1": 1 1 2 2 1 2 1 2 2 2 ...
 $ am  : Factor w/ 2 levels "0","1": 2 2 2 1 1 1 1 1 1 1 ...
 $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
 $ carb: num  4 4 1 1 2 1 4 2 2 4 ...

<br>

<font color=red>Task 2.2</font> Use the `levels()` function to determine the unique categories in the `vs` and `am` variables.

In [11]:
# check levels `vs`
levels(mtcars$vs)

# check levels `am`
levels(mtcars$am)

[1] "0" "1"

[1] "0" "1"

<br>

<font color=red>Task 2.3</font> Rewrite the levels so that they are more descriptive.

For example, for `am`, change the levels to be `'automatic'` for `'0'` and `'manual'` for `'1'`".

Check the levels to verify these changes.

In [12]:
# `vs` 0 "V-shaped" and 1 "Straight"
levels(mtcars$vs) <- c("V-shaped", "Straight")
levels(mtcars$vs) # check

# `am` 0 "Automatic" and 1 "Manual"
levels(mtcars$am) <- c("automatic", "manual")
levels(mtcars$am) #check

[1] "V-shaped" "Straight"

[1] "automatic" "manual"

<br>

<font color=red>Task 2.4</font> Use the `table()` function to determine the number of cars that have automatic transmission in the data frame.

In a text cell, write your observations.

In [13]:
table(mtcars$am)

automatic    manual
       19        13

There are 19 cars in the dataset that have an automatic transmission. There are 13 cars in the dataset that have a manual transmission.

<br>

<font color=red>Task 2.5</font> The `cyl` variable specifies the number of cylinders in the engine of the corresponding car.

* Convert the `cyl` variable into a factor and overwrite in the `mtcars` data frame
* Find the number of unique levels using the `length()` and `levels()` functions.

In [14]:
# convert to factor & overwrite original column
mtcars$cyl <- as.factor(mtcars$cyl)

# check levels
levels(mtcars$cyl)

# number of uniquie levels
length(levels(mtcars$cyl))

[1] "4" "6" "8"

[1] 3

There are 3 unique levels for the `cyl` variable.

<br>

<font color=red>Task 2.6</font> In a text cell, identify all other variables that should be a `factor` data structure.

In [15]:
# comvert to factor & overwrite original
mtcars$gear <- as.factor(mtcars$gear)

# check class
str(mtcars$gear)

# check levels
levels(mtcars$gear)

 Factor w/ 3 levels "3","4","5": 2 2 2 1 1 1 1 2 2 2 ...

[1] "3" "4" "5"

A case could be made for changing the variable `gear` to a `factor` class.

<br>

<br>

---

####<font color=red>Task 3</font> - Vectorized Operations

<font color=red>Task 3.1</font> Engine displacement is the total volume of air that an engine's pistons move in its cylinders.

Calculate engine displacement per cylinder and save it as a new variable called `UnitEngine` in the `mtcars` data frame. Use the `head()` function to verify you answer.
* Note displacement per cylinder is defined by `disp` divided by `cyl`.

In [16]:
# check levels of factor
levels(mtcars$cyl)

# converting `cyl` to numeric results in factor labels 1, 2, 3, being saved as the values
test <- as.character(mtcars$cyl)

# to get back to the original values of 4, 6, 8, we must first convert to factor

[1] "4" "6" "8"

In [17]:
# NOTE: `cyl` must be converted to character THEN NUMERIC for this to work
cyl_numeric <- as.numeric(as.character(mtcars$cyl))

# define new variable `Unitengine`
mtcars$Unitengine <- mtcars$disp / cyl_numeric

# check
head(mtcars)

                  mpg  cyl disp hp  drat wt    qsec  vs       am        gear
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 V-shaped manual    4
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 V-shaped manual    4
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 Straight manual    4
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 Straight automatic 3
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 V-shaped automatic 3
Valiant           18.1 6   225  105 2.76 3.460 20.22 Straight automatic 3
                  carb Unitengine
Mazda RX4         4    26.66667
Mazda RX4 Wag     4    26.66667
Datsun 710        1    27.00000
Hornet 4 Drive    1    43.00000
Hornet Sportabout 2    45.00000
Valiant           1    37.50000

<br>

<font color=red>Task 3.2</font> Calculate the average engine displacement of all the cars in the dataset using the `mean()` function.

In [20]:
# mean of `Unitengine`
mean(mtcars$Unitengine)

[1] 35.02865

In [21]:
summary(mtcars)

      mpg        cyl         disp             hp             drat
 Min.   :10.40   4:11   Min.   : 71.1   Min.   : 52.0   Min.   :2.760
 1st Qu.:15.43   6: 7   1st Qu.:120.8   1st Qu.: 96.5   1st Qu.:3.080
 Median :19.20   8:14   Median :196.3   Median :123.0   Median :3.695
 Mean   :20.09          Mean   :230.7   Mean   :146.7   Mean   :3.597
 3rd Qu.:22.80          3rd Qu.:326.0   3rd Qu.:180.0   3rd Qu.:3.920
 Max.   :33.90          Max.   :472.0   Max.   :335.0   Max.   :4.930
       wt             qsec              vs             am     gear
 Min.   :1.513   Min.   :14.50   V-shaped:18   automatic:19   3:15
 1st Qu.:2.581   1st Qu.:16.89   Straight:14   manual   :13   4:12
 Median :3.325   Median :17.71                                5: 5
 Mean   :3.217   Mean   :17.85
 3rd Qu.:3.610   3rd Qu.:18.90
 Max.   :5.424   Max.   :22.90
      carb         Unitengine
 Min.   :1.000   Min.   :17.77
 1st Qu.:2.000   1st Qu.:26.92
 Median :2.000   Median :34.48
 Mean   :2.812   Mean   :35.03
 3rd Qu.:4.000   3rd Qu.:43.19
 Max.   :8.000   Max.   :59.00

<br>