# **Practice 11: Loops - `for`, `while`, `repeat`**

#### **Kelani Guyton**

---

**IMPORTANT**:
- Before starting the lab, save a copy to your google drive by navigating to `File > Save a copy in Drive` <br>

<br>


**Instructions**: Complete the lab below.

- <font color=red>Tasks</font> indicated in red must be completed to receive credit
- Include all code for your work
- Include markdown cells with written answers explaining your work when prompted
- **NOTE: Your completed lab must be submitted to Canvas as a .ipynb file by the end of the lab session**
---

<br>

####<font color=red>Organized</font>

**Answers should be organized in the following format for organization and readability**

<font color=red>Example task 1</font>

In [ ]:
# 1.

# This will be the code block to answer the first part of a task

1. This will be the text answer/explanation (if prompted) for the first task

<font color=red>Example task 2</font>

In [ ]:
# 2.

# This will be the code block to answer the second part of a task

2. This will be the text answer/explanation (if prompted) for the second task

<br>

Continue this format for the remaining subtasks

<br>

---

<br>

#### Packages

In [ ]:
# none

<br>

<br>

<br>

---

####<font color=red>Task 1</font> - Loading and Preprocessing the Dataset

<font color=red>Task 1.1</font> Today, we'll be working with salary data available online.

* Run the following script to load the salary dataset for today's assignment.

```
# load data frame
data_url                       <- "https://raw.githubusercontent.com/khasenst/datasets_teaching/refs/heads/main/salary_data.csv"
salary                         <- na.omit(read.csv(data_url, header = TRUE))

# convert character variables to factors
salary$Gender                  <- as.factor(salary$Gender)
salary$Education.Level         <- as.factor(salary$Education.Level)
salary$Job.Title               <- as.factor(salary$Job.Title)

# reassign levels
levels(salary$Education.Level) <-  c("missing", "BS", "BS", "HS",
                                     "MS", "MS", "PhD", "PhD")
salary$Education.Level         <- factor(salary$Education.Level, levels = c("missing", "HS", "BS", "MS", "PhD"))
```

In [1]:
# load data frame
data_url                       <- "https://raw.githubusercontent.com/khasenst/datasets_teaching/refs/heads/main/salary_data.csv"
salary                         <- na.omit(read.csv(data_url, header = TRUE))

# convert character variables to factors
salary$Gender                  <- as.factor(salary$Gender)
salary$Education.Level         <- as.factor(salary$Education.Level)
salary$Job.Title               <- as.factor(salary$Job.Title)

# reassign levels
levels(salary$Education.Level) <-  c("missing", "BS", "BS", "HS",
                                     "MS", "MS", "PhD", "PhD")
salary$Education.Level         <- factor(salary$Education.Level, levels = c("missing", "HS", "BS", "MS", "PhD"))

<br>

<font color=red>Task 1.2</font> View the first few lines of the `salary` data frame using the `head()` function.

In [2]:
head(salary)

  Age Gender Education.Level Job.Title         Years.of.Experience Salary
1 32  Male   BS              Software Engineer  5                   90000
2 28  Female MS              Data Analyst       3                   65000
3 45  Male   PhD             Senior Manager    15                  150000
4 36  Female BS              Sales Associate    7                   60000
5 52  Male   MS              Director          20                  200000
6 29  Male   BS              Marketing Analyst  2                   55000

<br>

<br>

<br>

---

####<font color=red>Task 2</font> Using `for` loops for data exploration

<font color=red>Task 2.1</font>

* Use the `levels()` function to extract the unique values of the education variable in the `salary` data frame and store as the variable `education_levels`.

* Use subsetting to show that the second entry of your defined `education_levels` variable is `"HS"`

In [3]:
# extract levels
education_levels <- levels(salary$Education.Level)
education_levels

[1] "missing" "HS"      "BS"      "MS"      "PhD"

In [4]:
# subset for 2nd entry
education_levels[2]

[1] "HS"

<br>

<font color=red>Task 2.2</font>

* Write a `for` loop that iterates a vector of consecutive integers from `1` through the total number of education levels

* The `for` loop should print the corresponding education level at each iteration

In [5]:
# for loop
for(i in 1:length(education_levels)) {
  print(education_levels[i])
}

[1] "missing"
[1] "HS"
[1] "BS"
[1] "MS"
[1] "PhD"

<br>

<font color=red>Task 2.3</font>

* Use subsetting to calculate the average salary of individuals with an education level equal to the first entry of your defined `education_levels` variable.

In [6]:
# mean for 1st entry in education_levels - "missing"
mean(salary$Salary[salary$Education.Level == education_levels[1]])

[1] 1e+05

<br>

<font color=red>Task 2.4</font>

* Change your `for` loop from Task 2.2 to print the average salary of individuals in each education level

In [9]:
# for loop
for(i in 1:length(education_levels)) {

  # mean for subset by education level
  print(mean(salary$Salary[salary$Education.Level == education_levels[i]]))
}

[1] 1e+05
[1] 36706.69
[1] 95082.91
[1] 130112.1
[1] 165651.5

<br>

<font color=red>Task 2.5</font>

* Change your `for` loop from Task 2.4 iteratively store the computed average salaries in a variable called `salary_averages` (instead of printing them)

In [10]:
# vector to store means
salary_averages <- vector(length = length(education_levels))

# for loop
for(i in 1:length(education_levels)) {

  # mean for subset by education level
  salary_averages[i] <- (mean(salary$Salary[salary$Education.Level == education_levels[i]]))
}

# check
salary_averages

[1] 100000.00  36706.69  95082.91 130112.06 165651.46

<br>

<font color=red>Task 2.6</font>

Create a data frame using your `for` loop output with the following attributes
  * The data frame should have two columns: one for education level called `education_level` and one for average salary called `salary_average`
  * Each row of the data frame should corresponding to an education level

In [11]:
# data frame
data.frame(education_level = education_levels, salary_average = salary_averages)

  education_level salary_average
1 missing         100000.00
2 HS               36706.69
3 BS               95082.91
4 MS              130112.06
5 PhD             165651.46

In [12]:
# EXTRA

# define empty data frame to store levels & means
dat <- data.frame(education_level = NA, salary_average = NA)

# for loop
for(i in 1:length(education_levels)) {

  # fill in education level
  dat[i, 1] <- education_levels[i]

  # mean for subset by education level
  dat[i, 2] <- (mean(salary$Salary[salary$Education.Level == education_levels[i]]))
}

# check
dat

  education_level salary_average
1 missing         100000.00
2 HS               36706.69
3 BS               95082.91
4 MS              130112.06
5 PhD             165651.46

<br>

<font color=red>Task 2.7</font>

In a text cell, write your observations from the data frame you created in Task 2.6

From the summary table, we can observe that the average salary increases with education level.

<br>

<br>

<br>

---

####<font color=red>Task 3</font> Using `for` loops for data exploration

<font color=red>Task 3.1</font>

Using code similar to Task 2, create a data frame with the following attributes

* The data frame should have two columns: one for job title called `job` and one for average salary called `salary_average`

* Each row of the data frame should corresponding to unique job title

* Store the data frame as a variable called `job_salaries`

<br>

In [16]:
# vector or unique levels
job_titles <- levels(salary$Job.Title)
length(levels(salary$Job.Title))

# vector to store averages
salary_averages <- vector(length = length(job_titles))

# for loop
for(i in 1:length(job_titles)){
  salary_averages[i] <- mean(salary$Salary[salary$Job.Title == job_titles[i]])
}

# data frame
job_salaries <- data.frame(job = job_titles, salary_average = salary_averages)

# check
job_salaries

[1] 192

    job                              salary_average
1   Account Manager                   75000.00
2   Accountant                        55000.00
3   Administrative Assistant          50000.00
4   Back end Developer               102352.56
5   Business Analyst                  77500.00
6   Business Development Manager      90000.00
7   Business Intelligence Analyst     85000.00
8   CEO                              250000.00
9   Chief Data Officer               220000.00
10  Chief Technology Officer         250000.00
11  Content Marketing Manager        123150.68
12  Copywriter                        40000.00
13  Creative Director                120000.00
14  Customer Service Manager         105000.00
15  Customer Service Rep              40000.00
16  Customer Service Representative   33333.33
17  Customer Success Manager          40000.00
18  Customer Success Rep              40000.00
19  Data Analyst                     125090.91
20  Data Entry Clerk                  35000.00
21  Data Scientist                   166105.96
22  Delivery Driver                   28000.00
23  Developer                        100000.00
24  Digital Content Producer          50000.00
25  Digital Marketing Manager         93269.23
26  Digital Marketing Specialist      63333.33
27  Director                         200000.00
28  Director of Business Development 170000.00
29  Director of Data Science         204561.40
30  Director of Engineering          180000.00
⋮   ⋮                                ⋮
163 Senior Research Scientist        137959.18
164 Senior Researcher                150000.00
165 Senior Sales Manager             132500.00
166 Senior Sales Representative       95000.00
167 Senior Scientist                 123333.33
168 Senior Software Architect        120000.00
169 Senior Software Developer        118333.33
170 Senior Software Engineer         151326.69
171 Senior Training Specialist       100000.00
172 Senior UX Designer               155000.00
173 Social Media Man                 100000.00
174 Social Media Manager              55000.00
175 Social Media Specialist           45000.00
176 Software Developer                64680.00
177 Software Engineer                113243.24
178 Software Engineer Manager        172502.17
179 Software Manager                 110000.00
180 Software Project Manager          95000.00
181 Strategy Consultant              130000.00
182 Supply Chain Analyst             130000.00
183 Supply Chain Manager             105000.00
184 Technical Recruiter               70000.00
185 Technical Support Specialist      40000.00
186 Technical Writer                  45000.00
187 Training Specialist               65000.00
188 UX Designer                       80000.00
189 UX Researcher                     65000.00
190 VP of Finance                    200000.00
191 VP of Operations                 190000.00
192 Web Developer                     66436.78

<font color=red>Task 3.2</font>

* Use the `order()` function to order the data frame from highest average salary to lowest average salary and store as another data frame

In [17]:
# reorder rows
job_salaries_ord <- job_salaries[order(job_salaries$salary_average, decreasing = TRUE), ]

# check
job_salaries_ord

    job                                   salary_average
8   CEO                                   250000.0
10  Chief Technology Officer              250000.0
9   Chief Data Officer                    220000.0
29  Director of Data Science              204561.4
27  Director                              200000.0
190 VP of Finance                         200000.0
103 Operations Director                   190000.0
191 VP of Operations                      190000.0
34  Director of Human Resources           187500.0
97  Marketing Director                    183984.4
30  Director of Engineering               180000.0
33  Director of Human Capital             180000.0
39  Director of Sales and Marketing       180000.0
52  Human Resources Director              180000.0
31  Director of Finance                   175000.0
37  Director of Product Management        175000.0
38  Director of Sales                     175000.0
36  Director of Operations                172727.3
178 Software Engineer Manager             172502.2
28  Director of Business Development      170000.0
105 Principal Engineer                    170000.0
160 Senior Project Engineer               166224.8
21  Data Scientist                        166106.0
116 Research Scientist                    165362.3
115 Research Director                     163333.3
146 Senior Manager                        160000.0
149 Senior Marketing Director             160000.0
129 Senior Data Analyst                   155000.0
130 Senior Data Engineer                  155000.0
172 Senior UX Designer                    155000.0
⋮   ⋮                                     ⋮
91  Junior Web Designer                   45000.00
175 Social Media Specialist               45000.00
186 Technical Writer                      45000.00
122 Sales Representative                  44078.95
119 Sales Executive                       43026.32
94  Juniour HR Generalist                 43000.00
58  Junior Accountant                     41666.67
61  Junior Business Development Associate 40714.29
12  Copywriter                            40000.00
15  Customer Service Rep                  40000.00
17  Customer Success Manager              40000.00
18  Customer Success Rep                  40000.00
67  Junior Designer                       40000.00
68  Junior Developer                      40000.00
78  Junior Operations Coordinator         40000.00
185 Technical Support Specialist          40000.00
72  Junior HR Generalist                  38250.00
71  Junior HR Coordinator                 37017.24
85  Junior Sales Representative           36951.22
117 Sales Associate                       35857.14
88  Junior Software Developer             35810.34
20  Data Entry Clerk                      35000.00
48  Help Desk Analyst                     35000.00
64  Junior Customer Support Specialist    35000.00
16  Customer Service Representative       33333.33
93  Juniour HR Coordinator                32000.00
84  Junior Sales Associate                28211.27
22  Delivery Driver                       28000.00
113 Receptionist                          25000.00
62  Junior Business Operations Analyst    17675.00

<br>

<font color=red>Task 3.3</font>

* Show the `head()` and `tail()` of the ordered data frame from Task 3.2
* Which jobs have the highest and lowest average salaries?

In [18]:
# first 6 rows
head(job_salaries_ord)

# last 6 rows
tail(job_salaries_ord)

    job                      salary_average
8   CEO                      250000.0
10  Chief Technology Officer 250000.0
9   Chief Data Officer       220000.0
29  Director of Data Science 204561.4
27  Director                 200000.0
190 VP of Finance            200000.0

    job                                salary_average
16  Customer Service Representative    33333.33
93  Juniour HR Coordinator             32000.00
84  Junior Sales Associate             28211.27
22  Delivery Driver                    28000.00
113 Receptionist                       25000.00
62  Junior Business Operations Analyst 17675.00

The jobs that have the highest average salaries are CEO, Chief Technology Officer, Chief Data Officer, Director of Data Science, Director, and VP of Finance. The jobs that have the lowest average salaries are Customer Service Representaitve, Junior HR Coordinatoe, Junior Sales Associate, Delivery Driver, Receptionist, and Junior Business Operations Analyst.