# **Practice 13: Importing/Exporting Data**

#### **Kelani Guyton**

---

**IMPORTANT**:
- Before starting the lab, save a copy to your google drive by navigating to `File > Save a copy in Drive` <br>

<br>


**Instructions**: Complete the lab below.

- <font color=red>Tasks</font> indicated in red must be completed to receive credit
- Include all code for your work
- Include markdown cells with written answers explaining your work when prompted
- **NOTE: Your completed lab must be submitted to Canvas as a .ipynb file by the end of the lab session**
---

<br>

####<font color=red>Organized</font>

**Answers should be organized in the following format for organization and readability**

<font color=red>Example task 1</font>

In [ ]:
# 1.

# This will be the code block to answer the first part of a task

1. This will be the text answer/explanation (if prompted) for the first task

<font color=red>Example task 2</font>

In [ ]:
# 2.

# This will be the code block to answer the second part of a task

2. This will be the text answer/explanation (if prompted) for the second task

<br>

Continue this format for the remaining subtasks

<br>

---

<br>

#### Packages

In [1]:
# install packages
install.packages("dslabs")
install.packages("readxl")   # imports excel spreadsheets
install.packages("writexl")  # exports excel spreadsheets

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [2]:
# load libraries
library(dslabs)
library(readxl)
library(writexl)

<br>

<br>

<br>

---

####<font color=red>Task 1</font>

* The goal of this assignment is to load data contained in separate folder locations.

* We will use our knowledge of importing data and directory navigation.

<br>

<font color=red>Task 1.1</font> Downloading our data

* Run the following script to download our salary data in file directory format

  ```
  source("https://raw.githubusercontent.com/khasenst/datasets_teaching/refs/heads/main/salary_parse.R")
  ```

In [3]:
source("https://raw.githubusercontent.com/khasenst/datasets_teaching/refs/heads/main/salary_parse.R")

<br>

<font color=red>Task 1.2</font>

* Use the `getwd()` command to view your current working directory

* Use the `list.files()` command to view the files in your current working directory

In [4]:
getwd()

[1] "/content"

In [5]:
list.files()

[1] "salary_data" "sample_data"

<br>

<font color=red>Task 1.3</font>

* Use the `setwd()` function to change your current working directory to the `salary_data` folder containing our data

* Use `getwd()` to ensure you are in the correct directory

* Use the `list.files()` function to view which files are in the `salary_data` folder. What do you observe?

In [6]:
# set working director to folder in content
setwd('/content/salary_data')

In [7]:
# check current current working directory
getwd()

[1] "/content/salary_data"

In [8]:
# check files in the `salary_data`
list.files()

  [1] "Account Manager"
  [2] "Accountant"
  [3] "Administrative Assistant"
  [4] "Back end Developer"
  [5] "Business Analyst"
  [6] "Business Development Manager"
  [7] "Business Intelligence Analyst"
  [8] "CEO"
  [9] "Chief Data Officer"
 [10] "Chief Technology Officer"
 [11] "Content Marketing Manager"
 [12] "Copywriter"
 [13] "Creative Director"
 [14] "Customer Service Manager"
 [15] "Customer Service Rep"
 [16] "Customer Service Representative"
 [17] "Customer Success Manager"
 [18] "Customer Success Rep"
 [19] "Data Analyst"
 [20] "Data Entry Clerk"
 [21] "Data Scientist"
 [22] "Delivery Driver"
 [23] "Developer"
 [24] "Digital Content Producer"
 [25] "Digital Marketing Manager"
 [26] "Digital Marketing Specialist"
 [27] "Director"
 [28] "Director of Business Development"
 [29] "Director of Data Science"
 [30] "Director of Engineering"
 [31] "Director of Finance"
 [32] "Director of HR"
 [33] "Director of Human Capital"
 [34] "Director of Human Resources"
 [35] "Director of Marketing"
 [36] "Director of Operations"
 [37] "Director of Product Management"
 [38] "Director of Sales"
 [39] "Director of Sales and Marketing"
 [40] "Event Coordinator"
 [41] "Financial Advisor"
 [42] "Financial Analyst"
 [43] "Financial Manager"
 [44] "Front end Developer"
 [45] "Front End Developer"
 [46] "Full Stack Engineer"
 [47] "Graphic Designer"
 [48] "Help Desk Analyst"
 [49] "HR Generalist"
 [50] "HR Manager"
 [51] "Human Resources Coordinator"
 [52] "Human Resources Director"
 [53] "Human Resources Manager"
 [54] "IT Manager"
 [55] "IT Support"
 [56] "IT Support Specialist"
 [57] "Junior Account Manager"
 [58] "Junior Accountant"
 [59] "Junior Advertising Coordinator"
 [60] "Junior Business Analyst"
 [61] "Junior Business Development Associate"
 [62] "Junior Business Operations Analyst"
 [63] "Junior Copywriter"
 [64] "Junior Customer Support Specialist"
 [65] "Junior Data Analyst"
 [66] "Junior Data Scientist"
 [67] "Junior Designer"
 [68] "Junior Developer"
 [69] "Junior Financial Advisor"
 [70] "Junior Financial Analyst"
 [71] "Junior HR Coordinator"
 [72] "Junior HR Generalist"
 [73] "Junior Marketing Analyst"
 [74] "Junior Marketing Coordinator"
 [75] "Junior Marketing Manager"
 [76] "Junior Marketing Specialist"
 [77] "Junior Operations Analyst"
 [78] "Junior Operations Coordinator"
 [79] "Junior Operations Manager"
 [80] "Junior Product Manager"
 [81] "Junior Project Manager"
 [82] "Junior Recruiter"
 [83] "Junior Research Scientist"
 [84] "Junior Sales Associate"
 [85] "Junior Sales Representative"
 [86] "Junior Social Media Manager"
 [87] "Junior Social Media Specialist"
 [88] "Junior Software Developer"
 [89] "Junior Software Engineer"
 [90] "Junior UX Designer"
 [91] "Junior Web Designer"
 [92] "Junior Web Developer"
 [93] "Juniour HR Coordinator"
 [94] "Juniour HR Generalist"
 [95] "Marketing Analyst"
 [96] "Marketing Coordinator"
 [97] "Marketing Director"
 [98] "Marketing Manager"
 [99] "Marketing Specialist"
[100] "Network Engineer"
[101] "Office Manager"
[102] "Operations Analyst"
[103] "Operations Director"
[104] "Operations Manager"
[105] "Principal Engineer"
[106] "Principal Scientist"
[107] "Product Designer"
[108] "Product Manager"
[109] "Product Marketing Manager"
[110] "Project Engineer"
[111] "Project Manager"
[112] "Public Relations Manager"
[113] "Receptionist"
[114] "Recruiter"
[115] "Research Director"
[116] "Research Scientist"
[117] "Sales Associate"
[118] "Sales Director"
[119] "Sales Executive"
[120] "Sales Manager"
[121] "Sales Operations Manager"
[122] "Sales Representative"
[123] "Senior Account Executive"
[124] "Senior Account Manager"
[125] "Senior Accountant"
[126] "Senior Business Analyst"
[127] "Senior Business Development Manager"
[128] "Senior Consultant"
[129] "Senior Data Analyst"
[130] "Senior Data Engineer"
[131] "Senior Data Scientist"
[132] "Senior Engineer"
[133] "Senior Financial Advisor"
[134] "Senior Financial Analyst"
[135] "Senior Financial Manager"
[136] "Senior Graphic Designer"
[137] "Senior HR Generalist"
[138] "Senior HR Manager"
[139] "Senior HR Specialist"
[140] "Senior Human Resources Coordinator"
[141] "Senior Human Resources Manager"
[142] "Senior Human Resources Specialist"
[143] "Senior IT Consultant"
[144] "Senior IT Project Manager"
[145] "Senior IT Support Specialist"
[146] "Senior Manager"
[147] "Senior Marketing Analyst"
[148] "Senior Marketing Coordinator"
[149] "Senior Marketing Director"
[150] "Senior Marketing Manager"
[151] "Senior Marketing Specialist"
[152] "Senior Operations Analyst"
[153] "Senior Operations Coordinator"
[154] "Senior Operations Manager"
[155] "Senior Product Designer"
[156] "Senior Product Development Manager"
[157] "Senior Product Manager"
[158] "Senior Product Marketing Manager"
[159] "Senior Project Coordinator"
[160] "Senior Project Engineer"
[161] "Senior Project Manager"
[162] "Senior Quality Assurance Analyst"
[163] "Senior Research Scientist"
[164] "Senior Researcher"
[165] "Senior Sales Manager"
[166] "Senior Sales Representative"
[167] "Senior Scientist"
[168] "Senior Software Architect"
[169] "Senior Software Developer"
[170] "Senior Software Engineer"
[171] "Senior Training Specialist"
[172] "Senior UX Designer"
[173] "Social Media Man"
[174] "Social Media Manager"
[175] "Social Media Specialist"
[176] "Software Developer"
[177] "Software Engineer"
[178] "Software Engineer Manager"
[179] "Software Manager"
[180] "Software Project Manager"
[181] "Strategy Consultant"
[182] "Supply Chain Analyst"
[183] "Supply Chain Manager"
[184] "Technical Recruiter"
[185] "Technical Support Specialist"
[186] "Technical Writer"
[187] "Training Specialist"
[188] "UX Designer"
[189] "UX Researcher"
[190] "VP of Finance"
[191] "VP of Operations"
[192] "Web Developer"

There are many files. One for each unique job title.

<br>

<font color=red>Task 1.4</font>

* Use the `list.files()` function to view all the files in the "Data Scientist" folder

* What type of files are in the folder?

In [9]:
list.files("/content/salary_data/Data Scientist")

  [1] "entry1.csv"   "entry10.csv"  "entry100.csv" "entry101.csv" "entry102.csv"
  [6] "entry103.csv" "entry104.csv" "entry105.csv" "entry106.csv" "entry107.csv"
 [11] "entry108.csv" "entry109.csv" "entry11.csv"  "entry110.csv" "entry111.csv"
 [16] "entry112.csv" "entry113.csv" "entry114.csv" "entry115.csv" "entry116.csv"
 [21] "entry117.csv" "entry118.csv" "entry119.csv" "entry12.csv"  "entry120.csv"
 [26] "entry121.csv" "entry122.csv" "entry123.csv" "entry124.csv" "entry125.csv"
 [31] "entry126.csv" "entry127.csv" "entry128.csv" "entry129.csv" "entry13.csv"
 [36] "entry130.csv" "entry131.csv" "entry132.csv" "entry133.csv" "entry134.csv"
 [41] "entry135.csv" "entry136.csv" "entry137.csv" "entry138.csv" "entry139.csv"
 [46] "entry14.csv"  "entry140.csv" "entry141.csv" "entry142.csv" "entry143.csv"
 [51] "entry144.csv" "entry145.csv" "entry146.csv" "entry147.csv" "entry148.csv"
 [56] "entry149.csv" "entry15.csv"  "entry150.csv" "entry151.csv" "entry152.csv"
 [61] "entry153.csv" "entry154.csv" "entry155.csv" "entry156.csv" "entry157.csv"
 [66] "entry158.csv" "entry159.csv" "entry16.csv"  "entry160.csv" "entry161.csv"
 [71] "entry162.csv" "entry163.csv" "entry164.csv" "entry165.csv" "entry166.csv"
 [76] "entry167.csv" "entry168.csv" "entry169.csv" "entry17.csv"  "entry170.csv"
 [81] "entry171.csv" "entry172.csv" "entry173.csv" "entry174.csv" "entry175.csv"
 [86] "entry176.csv" "entry177.csv" "entry178.csv" "entry179.csv" "entry18.csv"
 [91] "entry180.csv" "entry181.csv" "entry182.csv" "entry183.csv" "entry184.csv"
 [96] "entry185.csv" "entry186.csv" "entry187.csv" "entry188.csv" "entry189.csv"
[101] "entry19.csv"  "entry190.csv" "entry191.csv" "entry192.csv" "entry193.csv"
[106] "entry194.csv" "entry195.csv" "entry196.csv" "entry197.csv" "entry198.csv"
[111] "entry199.csv" "entry2.csv"   "entry20.csv"  "entry200.csv" "entry201.csv"
[116] "entry202.csv" "entry203.csv" "entry204.csv" "entry205.csv" "entry206.csv"
[121] "entry207.csv" "entry208.csv" "entry209.csv" "entry21.csv"  "entry210.csv"
[126] "entry211.csv" "entry212.csv" "entry213.csv" "entry214.csv" "entry215.csv"
[131] "entry216.csv" "entry217.csv" "entry218.csv" "entry219.csv" "entry22.csv"
[136] "entry220.csv" "entry221.csv" "entry222.csv" "entry223.csv" "entry224.csv"
[141] "entry225.csv" "entry226.csv" "entry227.csv" "entry228.csv" "entry229.csv"
[146] "entry23.csv"  "entry230.csv" "entry231.csv" "entry232.csv" "entry233.csv"
[151] "entry234.csv" "entry235.csv" "entry236.csv" "entry237.csv" "entry238.csv"
[156] "entry239.csv" "entry24.csv"  "entry240.csv" "entry241.csv" "entry242.csv"
[161] "entry243.csv" "entry244.csv" "entry245.csv" "entry246.csv" "entry247.csv"
[166] "entry248.csv" "entry249.csv" "entry25.csv"  "entry250.csv" "entry251.csv"
[171] "entry252.csv" "entry253.csv" "entry254.csv" "entry255.csv" "entry256.csv"
[176] "entry257.csv" "entry258.csv" "entry259.csv" "entry26.csv"  "entry260.csv"
[181] "entry261.csv" "entry262.csv" "entry263.csv" "entry264.csv" "entry265.csv"
[186] "entry266.csv" "entry267.csv" "entry268.csv" "entry269.csv" "entry27.csv"
[191] "entry270.csv" "entry271.csv" "entry272.csv" "entry273.csv" "entry274.csv"
[196] "entry275.csv" "entry276.csv" "entry277.csv" "entry278.csv" "entry279.csv"
[201] "entry28.csv"  "entry280.csv" "entry281.csv" "entry282.csv" "entry283.csv"
[206] "entry284.csv" "entry285.csv" "entry286.csv" "entry287.csv" "entry288.csv"
[211] "entry289.csv" "entry29.csv"  "entry290.csv" "entry291.csv" "entry292.csv"
[216] "entry293.csv" "entry294.csv" "entry295.csv" "entry296.csv" "entry297.csv"
[221] "entry298.csv" "entry299.csv" "entry3.csv"   "entry30.csv"  "entry300.csv"
[226] "entry301.csv" "entry302.csv" "entry303.csv" "entry304.csv" "entry305.csv"
[231] "entry306.csv" "entry307.csv" "entry308.csv" "entry309.csv" "entry31.csv"
[236] "entry310.csv" "entry311.csv" "entry312.csv" "entry313.csv" "entry314.csv"
[241] "entry315.csv" "entry316.csv" "entry317.csv" "entry318.csv" "entry319.csv"
[246] "entry32.csv"  "entry320.csv" "entry321.csv" "entry322.csv" "entry323.csv"
[251] "entry324.csv" "entry325.csv" "entry326.csv" "entry327.csv" "entry328.csv"
[256] "entry329.csv" "entry33.csv"  "entry330.csv" "entry331.csv" "entry332.csv"
[261] "entry333.csv" "entry334.csv" "entry335.csv" "entry336.csv" "entry337.csv"
[266] "entry338.csv" "entry339.csv" "entry34.csv"  "entry340.csv" "entry341.csv"
[271] "entry342.csv" "entry343.csv" "entry344.csv" "entry345.csv" "entry346.csv"
[276] "entry347.csv" "entry348.csv" "entry349.csv" "entry35.csv"  "entry350.csv"
[281] "entry351.csv" "entry352.csv" "entry353.csv" "entry354.csv" "entry355.csv"
[286] "entry356.csv" "entry357.csv" "entry358.csv" "entry359.csv" "entry36.csv"
[291] "entry360.csv" "entry361.csv" "entry362.csv" "entry363.csv" "entry364.csv"
[296] "entry365.csv" "entry366.csv" "entry367.csv" "entry368.csv" "entry369.csv"
[301] "entry37.csv"  "entry370.csv" "entry371.csv" "entry372.csv" "entry373.csv"
[306] "entry374.csv" "entry375.csv" "entry376.csv" "entry377.csv" "entry378.csv"
[311] "entry379.csv" "entry38.csv"  "entry380.csv" "entry381.csv" "entry382.csv"
[316] "entry383.csv" "entry384.csv" "entry385.csv" "entry386.csv" "entry387.csv"
[321] "entry388.csv" "entry389.csv" "entry39.csv"  "entry390.csv" "entry391.csv"
[326] "entry392.csv" "entry393.csv" "entry394.csv" "entry395.csv" "entry396.csv"
[331] "entry397.csv" "entry398.csv" "entry399.csv" "entry4.csv"   "entry40.csv"
[336] "entry400.csv" "entry401.csv" "entry402.csv" "entry403.csv" "entry404.csv"
[341] "entry405.csv" "entry406.csv" "entry407.csv" "entry408.csv" "entry409.csv"
[346] "entry41.csv"  "entry410.csv" "entry411.csv" "entry412.csv" "entry413.csv"
[351] "entry414.csv" "entry415.csv" "entry416.csv" "entry417.csv" "entry418.csv"
[356] "entry419.csv" "entry42.csv"  "entry420.csv" "entry421.csv" "entry422.csv"
[361] "entry423.csv" "entry424.csv" "entry425.csv" "entry426.csv" "entry427.csv"
[366] "entry428.csv" "entry429.csv" "entry43.csv"  "entry430.csv" "entry431.csv"
[371] "entry432.csv" "entry433.csv" "entry434.csv" "entry435.csv" "entry436.csv"
[376] "entry437.csv" "entry438.csv" "entry439.csv" "entry44.csv"  "entry440.csv"
[381] "entry441.csv" "entry442.csv" "entry443.csv" "entry444.csv" "entry445.csv"
[386] "entry446.csv" "entry447.csv" "entry448.csv" "entry449.csv" "entry45.csv"
[391] "entry450.csv" "entry451.csv" "entry452.csv" "entry453.csv" "entry46.csv"
[396] "entry47.csv"  "entry48.csv"  "entry49.csv"  "entry5.csv"   "entry50.csv"
[401] "entry51.csv"  "entry52.csv"  "entry53.csv"  "entry54.csv"  "entry55.csv"
[406] "entry56.csv"  "entry57.csv"  "entry58.csv"  "entry59.csv"  "entry6.csv"
[411] "entry60.csv"  "entry61.csv"  "entry62.csv"  "entry63.csv"  "entry64.csv"
[416] "entry65.csv"  "entry66.csv"  "entry67.csv"  "entry68.csv"  "entry69.csv"
[421] "entry7.csv"   "entry70.csv"  "entry71.csv"  "entry72.csv"  "entry73.csv"
[426] "entry74.csv"  "entry75.csv"  "entry76.csv"  "entry77.csv"  "entry78.csv"
[431] "entry79.csv"  "entry8.csv"   "entry80.csv"  "entry81.csv"  "entry82.csv"
[436] "entry83.csv"  "entry84.csv"  "entry85.csv"  "entry86.csv"  "entry87.csv"
[441] "entry88.csv"  "entry89.csv"  "entry9.csv"   "entry90.csv"  "entry91.csv"
[446] "entry92.csv"  "entry93.csv"  "entry94.csv"  "entry95.csv"  "entry96.csv"
[451] "entry97.csv"  "entry98.csv"  "entry99.csv"

The files are `.csv` which are comma seperated files.

<br>

<font color=red>Task 1.5</font>

* Load one of these files into `R` using one of the functions covered in lecture

In [10]:
data_dir <- "/content/salary_data"

dat <- read.csv(file.path(data_dir, "Data Scientist", "entry1.csv"), header = TRUE)

dat

  Age Gender Education.Level Job.Title      Years.of.Experience Salary
1 29  Male   MS              Data Scientist 3                   75000

In [11]:
dat2 <- read.csv("/content/salary_data/Data Scientist/entry1.csv", header = TRUE)
dat2

  Age Gender Education.Level Job.Title      Years.of.Experience Salary
1 29  Male   MS              Data Scientist 3                   75000

<br>

<br>

<br>

---

####<font color=red>Task 2</font>

<font color=red>Task 2.1</font>

* Write a `for` loop that loads each file in the "Data Scientist" folder and stores it into an unstructured list

  Pseudo code hint:
  ```
  # create empty list
  data <- list()

  # loop through files
  for (i in 1:number_of_files) {
    # store as entry in list
    data[[i]] <- read.file...
  }
  ```

In [12]:
# current working directory
data_dir <- "/content/salary_data"

# saving vector with all of the csv file names that are in the "Data Scientist" folder
file_list <- list.files(file.path(data_dir, "Data Scientist"))

# empty list to store data from csv files
data <- list()

# loop through the files addings to my unstructured list `data`
for(i in 1:length(file_list)) {
  # stor as entry in the list
  data[[i]] <- read.csv(file.path(data_dir, "Data Scientist", file_list[i]), header = TRUE)
}

data

[[1]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  29   Male              MS Data Scientist                   3  75000

[[2]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  33   Male             PhD Data Scientist                   8 190000

[[3]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  31 Female              MS Data Scientist                   6 180000

[[4]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30 Female             PhD Data Scientist                   7 185000

[[5]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  29 Female              MS Data Scientist                   6 180000

[[6]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30 Female             PhD Data Scientist                   7 185000

[[7]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  29 Female              MS Data Scientist                   6 180000

[[8]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30 Female             PhD Data Scientist                   7 185000

[[9]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  29 Female              MS Data Scientist                   6 180000

[[10]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30 Female             PhD Data Scientist                   7 185000

[[11]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  29 Female              MS Data Scientist                   6 180000

[[12]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30 Female             PhD Data Scientist                   7 185000

[[13]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30 Female             PhD Data Scientist                   5 180000

[[14]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  29 Female              MS Data Scientist                   6 180000

[[15]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30 Female             PhD Data Scientist                   7 185000

[[16]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  29 Female              MS Data Scientist                   6 180000

[[17]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30 Female             PhD Data Scientist                   7 185000

[[18]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  29 Female              MS Data Scientist                   6 180000

[[19]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30 Female             PhD Data Scientist                   7 185000

[[20]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  29 Female              MS Data Scientist                   6 180000

[[21]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30 Female             PhD Data Scientist                   7 185000

[[22]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  29 Female              MS Data Scientist                   6 180000

[[23]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30 Female             PhD Data Scientist                   7 185000

[[24]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  33   Male             PhD Data Scientist                   8 190000

[[25]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  29 Female              MS Data Scientist                   6 180000

[[26]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30 Female             PhD Data Scientist                   7 185000

[[27]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  27 Female              MS Data Scientist                   3 180000

[[28]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  43   Male              MS Data Scientist                  15 198000

[[29]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  31   Male              MS Data Scientist                   6 175000

[[30]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  29 Female              MS Data Scientist                   4 182000

[[31]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  32   Male              BS Data Scientist                   8 180000

[[32]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30 Female             PhD Data Scientist                   7 170000

[[33]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30   Male             PhD Data Scientist                   7 170000

[[34]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  29 Female              MS Data Scientist                   6 150000

[[35]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  27   Male             PhD Data Scientist                   2 115000

[[36]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  32   Male              BS Data Scientist                   8 180000

[[37]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  31 Female              MS Data Scientist                   6 170000

[[38]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30 Female             PhD Data Scientist                   7 170000

[[39]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  29 Female              MS Data Scientist                   6 150000

[[40]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30 Female             PhD Data Scientist                   7 170000

[[41]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  29 Female              MS Data Scientist                   6 150000

[[42]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30 Female             PhD Data Scientist                   7 170000

[[43]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  29 Female              MS Data Scientist                   6 150000

[[44]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30 Female             PhD Data Scientist                   7 170000

[[45]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  29 Female              MS Data Scientist                   6 150000

[[46]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  33   Male             PhD Data Scientist                   8 190000

[[47]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30 Female             PhD Data Scientist                   7 170000

[[48]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  29 Female              MS Data Scientist                   6 150000

[[49]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30 Female             PhD Data Scientist                   7 170000

[[50]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  29 Female              MS Data Scientist                   6 150000

[[51]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30 Female             PhD Data Scientist                   7 170000

[[52]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  29 Female              MS Data Scientist                   6 150000

[[53]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30 Female             PhD Data Scientist                   7 170000

[[54]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  29 Female              MS Data Scientist                   6 150000

[[55]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30 Female             PhD Data Scientist                   7 170000

[[56]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  29 Female              MS Data Scientist                   6 150000

[[57]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30 Female             PhD Data Scientist                   5 180000

[[58]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30 Female             PhD Data Scientist                   7 170000

[[59]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  29 Female              MS Data Scientist                   6 150000

[[60]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30 Female             PhD Data Scientist                   7 170000

[[61]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  33   Male              MS Data Scientist                  10 195000

[[62]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  32 Female              BS Data Scientist                   9 185000

[[63]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  28 Female              MS Data Scientist                   6 150000

[[64]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  31   Male              MS Data Scientist                   9 185000

[[65]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  28 Female              MS Data Scientist                   6 155000

[[66]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  33   Male              MS Data Scientist                  10 195000

[[67]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  32 Female              BS Data Scientist                   9 185000

[[68]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  33   Male             PhD Data Scientist                   8 190000

[[69]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  28 Female              MS Data Scientist                   6 150000

[[70]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  31   Male              MS Data Scientist                   9 185000

[[71]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  28 Female              MS Data Scientist                   6 155000

[[72]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  33   Male              MS Data Scientist                  10 195000

[[73]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  32 Female              BS Data Scientist                   9 185000

[[74]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  28 Female              MS Data Scientist                   6 150000

[[75]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  31   Male              MS Data Scientist                   9 185000

[[76]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  28 Female              MS Data Scientist                   6 155000

[[77]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  33   Male              MS Data Scientist                  10 195000

[[78]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  32 Female              BS Data Scientist                   9 185000

[[79]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  27   Male             PhD Data Scientist                   2 115000

[[80]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  28 Female              MS Data Scientist                   6 150000

[[81]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  31   Male              MS Data Scientist                   9 185000

[[82]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  28 Female              MS Data Scientist                   6 155000

[[83]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  33   Male              MS Data Scientist                  10 195000

[[84]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  32 Female              BS Data Scientist                   9 185000

[[85]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  28 Female              MS Data Scientist                   6 150000

[[86]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  31   Male              MS Data Scientist                   9 185000

[[87]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  28 Female              MS Data Scientist                   6 155000

[[88]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  38   Male              BS Data Scientist                  10 150000

[[89]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34   Male              MS Data Scientist                   9 140000

[[90]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  33   Male             PhD Data Scientist                   8 190000

[[91]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34   Male              MS Data Scientist                   9 140000

[[92]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34   Male              MS Data Scientist                   9 140000

[[93]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34   Male              MS Data Scientist                   9 140000

[[94]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34   Male              MS Data Scientist                   9 140000

[[95]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34   Male              MS Data Scientist                   9 140000

[[96]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34   Male              MS Data Scientist                   9 140000

[[97]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  41   Male             PhD Data Scientist                  15 190000

[[98]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  37 Female              MS Data Scientist                  11 160000

[[99]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  31   Male              MS Data Scientist                   7 130000

[[100]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34 Female              MS Data Scientist                   9 140000

[[101]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  27   Male             PhD Data Scientist                   2 115000

[[102]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34   Male              MS Data Scientist                   9 140000

[[103]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34   Male              MS Data Scientist                   9 140000

[[104]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34   Male              MS Data Scientist                   9 140000

[[105]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34   Male              MS Data Scientist                   9 140000

[[106]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34   Male              MS Data Scientist                   9 140000

[[107]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  36 Female              MS Data Scientist                   8 130000

[[108]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34   Male              MS Data Scientist                   9 140000

[[109]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34   Male              MS Data Scientist                   9 140000

[[110]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34   Male              MS Data Scientist                   9 140000

[[111]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34   Male              MS Data Scientist                   9 140000

[[112]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  31   Male              MS Data Scientist                   6 160000

[[113]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  33   Male             PhD Data Scientist                   8 190000

[[114]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34   Male              MS Data Scientist                   9 140000

[[115]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34   Male              MS Data Scientist                   9 140000

[[116]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34   Male              MS Data Scientist                   9 140000

[[117]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34   Male              MS Data Scientist                   9 140000

[[118]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34   Male              MS Data Scientist                   9 140000

[[119]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34   Male              MS Data Scientist                   9 140000

[[120]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34   Male              MS Data Scientist                   9 140000

[[121]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34   Male              MS Data Scientist                   9 140000

[[122]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34   Male              MS Data Scientist                   9 140000

[[123]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  34   Male              MS Data Scientist                   9 140000

[[124]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  30 Female             PhD Data Scientist                   5 180000

[[125]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  43   Male             PhD Data Scientist                  15 150000

[[126]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  42   Male             PhD Data Scientist                  12 130000

[[127]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  45   Male             PhD Data Scientist                  18 180000

[[128]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  44   Male             PhD Data Scientist                  16 160000

[[129]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  42   Male             PhD Data Scientist                  13 140000

[[130]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  45   Male             PhD Data Scientist                  18 180000

[[131]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  44   Male             PhD Data Scientist                  16 160000

[[132]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  42   Male             PhD Data Scientist                  13 140000

[[133]]
  Age Gender Education.Level      Job.Title Years.of.Experience Salary
1  45   Male             PhD Data Scientist                  18 180000

[[134]]

<br>

<font color=red>Task 2.2</font>

* Use `do.call()` to combine all of the unstructured list items into a single data frame of all individuals who have the "Data Scientist" job title.

* Use the `head()` function to check your work

In [13]:
ds_data <- do.call(rbind, data)
head(ds_data)

  Age Gender Education.Level Job.Title      Years.of.Experience Salary
1 29  Male   MS              Data Scientist 3                    75000
2 33  Male   PhD             Data Scientist 8                   190000
3 31  Female MS              Data Scientist 6                   180000
4 30  Female PhD             Data Scientist 7                   185000
5 29  Female MS              Data Scientist 6                   180000
6 30  Female PhD             Data Scientist 7                   185000

<br>

<font color=red>Task 2.3</font>

* Use `dir.create()` to create a folder called "processed_data" in the file folder

* Export your data frame from Task 2.2 into the "processed_data" folder as a tab delimited file called "ds_salaries.txt"

* Export your data frame from Task 2.2 into the "processed_data" folder as an excel spreadsheet called "ds_salaries.xlsx"

In [14]:
# creat a folder called `process_data`
dir.create("/content/processed_data")

In [15]:
# export as txt
write.table(ds_data, "/content/processed_data/ds_salaries.txt",
            sep = "\t",
            row.names = FALSE)

In [16]:
# export as xlsx
write_xlsx(x = ds_data,
           path = "/content/processed_data/ds_salaries.xlsx")

<br>

<br>

<br>

---

####<font color=red>Extra Challenge (optional)</font>

<font color=red>Task E.1</font>

* Write down steps for how you would load data from all job titles into `R` as a single data frame

<br>

<font color=red>Task E.2</font>

* Try it out! This can be difficult when just learning `R`, but work with others and try your best.